from enum import Enum


class ToolErrorCode(str, Enum):
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    TOOL_UNAVAILABLE = "TOOL_UNAVAILABLE"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    POLICY_DENIED = "POLICY_DENIED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    REMOVED_TOOL = "REMOVED_TOOL"
    INVOCATION_FAILED_RETRYABLE = "INVOCATION_FAILED_RETRYABLE"
    INVOCATION_FAILED_TERMINAL = "INVOCATION_FAILED_TERMINAL"
